// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { LineEditInner } from "../common/common.slint";
import { StateLayer } from "comp-state-layer.slint";
import { md } from "md.slint";

// A selectable item that is used by `StandardListView` and  `ComboBox`.
export component Item inherits Rectangle { 
    callback clicked <=> state-layer.clicked;

    in property<bool> selected;
    in-out property<string> text;
    in property<bool> editable;

    // background: md.sys.color.background;
    height: 48px;

    state-layer := StateLayer {
        checked: root.selected;
        background: md.sys.color.primary;
        selection-background: md.sys.color.secondary-container; 
        ripple-color: md.sys.color.primary-ripple;
        has-ripple: true;
        enabled: !root.editable;
    }

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;

        Rectangle {  
            line-edit := LineEditInner {
                y: (parent.height - self.height) / 2;
                opacity: self.has-focus ? 1.0 : 0.0;
                visible: root.editable;
                text: root.text;
                font-size: label.font-size;

                edited => {  
                    root.text = self.text;
                }
            }

            label := Text {
                width: 100%;
                // height: 100%;
                visible: !root.editable || !line-edit.has-focus;
                text: root.text;
                color: md.sys.color.on-surface;
                vertical-alignment: center;
                horizontal-alignment: left;
                // FIXME after Roboto font can be loaded
                //font-family: md.sys.typescale.label-large.font;
                font-size: md.sys.typescale.label-large.size;
                font-weight: md.sys.typescale.label-large.weight;
            }
        }
    }

    states [  
        selected when root.selected : {
            state-layer.background: md.sys.color.secondary-container; 
        }    
    ] 
}